# Generated by Django 3.2 on 2022-10-24 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('industrial', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='show_on_main_page',
            field=models.BooleanField(default=True, verbose_name='на гл стр'),
        ),
    ]
