# Generated by Django 3.2 on 2022-10-24 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('industrial', '0003_applicant_show_on_main_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='qualification',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
