# Generated by Django 3.2 on 2022-10-26 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('industrial', '0004_alter_job_qualification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='show_on_main_page',
            field=models.BooleanField(default=True, verbose_name='на стр вакансии'),
        ),
        migrations.AlterField(
            model_name='companyreferralchain',
            name='affiliate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affiliate', to='industrial.company'),
        ),
        migrations.AlterField(
            model_name='companyreferralchain',
            name='referral',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='referral', to='industrial.company'),
        ),
    ]
