# Generated by Django 3.2 on 2022-10-26 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('industrial', '0005_auto_20221026_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='show_on_main_page',
            field=models.BooleanField(default=True, verbose_name='на стр вакансий'),
        ),
    ]
