# Generated by Django 3.2 on 2022-10-27 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_base', '0003_auto_20221027_0831'),
        ('industrial', '0006_alter_applicant_show_on_main_page'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicant',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='job',
            name='tags',
        ),
        migrations.AddField(
            model_name='applicant',
            name='tags_app',
            field=models.ManyToManyField(related_name='app_tegs', to='core_base.TagApp'),
        ),
        migrations.AddField(
            model_name='job',
            name='tags_job',
            field=models.ManyToManyField(related_name='job_tegs', to='core_base.Tag'),
        ),
    ]
