# Generated by Django 3.2 on 2022-10-31 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('industrial', '0009_auto_20221027_1428'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicant',
            name='category',
        ),
    ]
