# Generated by Django 3.2 on 2022-11-01 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('industrial', '0010_remove_applicant_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='have_tabel',
            field=models.BooleanField(default=False),
        ),
    ]
