# Generated by Django 3.2 on 2022-11-01 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('industrial', '0011_applicant_have_tabel'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='have_education',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='applicant',
            name='have_experience',
            field=models.BooleanField(default=False),
        ),
    ]
