# Generated by Django 3.2 on 2022-11-10 05:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core_base', '0010_individualtag'),
        ('industrial', '0013_alter_applicant_tags_app'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='ind_tags',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ind_app_tegs', to='core_base.individualtag'),
        ),
        migrations.AddField(
            model_name='job',
            name='ind_tags',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ind_job_tegs', to='core_base.individualtag'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='status',
            field=models.CharField(choices=[('published', 'Опубликована'), ('not_published', 'Не опубликована')], default='published', max_length=20),
        ),
    ]
