# Generated by Django 3.2 on 2022-11-11 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core_base', '0011_auto_20221111_1447'),
        ('payment', '0001_initial'),
        ('industrial', '0014_auto_20221110_0854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='employment_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='apps', to='core_base.employmenttype'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='experience',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='apps', to='core_base.experience'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='ind_tags',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ind_app_tegs', to='core_base.individualtag'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='apps', to='core_base.location'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='salary_condition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='app_salary_condition', to='core_base.additionalsalarycondition'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='work_schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='apps', to='core_base.workschedule'),
        ),
        migrations.AlterField(
            model_name='companyfinancetransaction',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='industrial.company'),
        ),
        migrations.AlterField(
            model_name='companyfinancetransaction',
            name='payment_for_job',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment', to='industrial.job'),
        ),
        migrations.AlterField(
            model_name='companyfinancetransaction',
            name='payment_invoice',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transaction', to='payment.paymentinvoice'),
        ),
        migrations.AlterField(
            model_name='companyreferralchain',
            name='affiliate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='affiliate', to='industrial.company'),
        ),
        migrations.AlterField(
            model_name='companyreferralchain',
            name='referral',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='referral', to='industrial.company'),
        ),
        migrations.AlterField(
            model_name='job',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jobs', to='core_base.jobcategory'),
        ),
        migrations.AlterField(
            model_name='job',
            name='employment_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jobs', to='core_base.employmenttype'),
        ),
        migrations.AlterField(
            model_name='job',
            name='experience',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jobs', to='core_base.experience'),
        ),
        migrations.AlterField(
            model_name='job',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jobs', to='core_base.location'),
        ),
        migrations.AlterField(
            model_name='job',
            name='recruiter_communication_method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jobs', to='core_base.communicationmethod'),
        ),
        migrations.AlterField(
            model_name='job',
            name='salary_condition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='salary_additional_condition', to='core_base.additionalsalarycondition'),
        ),
        migrations.AlterField(
            model_name='job',
            name='work_schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jobs', to='core_base.workschedule'),
        ),
    ]
