# Generated by Django 3.2 on 2022-11-15 05:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core_base', '0012_alter_educationplace_applicant'),
        ('industrial', '0016_alter_applicant_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='salary_condition',
            field=models.ForeignKey(default='В месяц', on_delete=django.db.models.deletion.PROTECT, related_name='salary_additional_condition', to='core_base.additionalsalarycondition'),
        ),
    ]
