# Generated by Django 3.2 on 2022-11-16 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core_base', '0012_alter_educationplace_applicant'),
        ('payment', '0002_alter_paymentinvoice_company'),
        ('industrial', '0017_alter_job_salary_condition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='ind_tags',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='ind_app_tegs', to='core_base.individualtag'),
        ),
        migrations.AlterField(
            model_name='companyfinancetransaction',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='transactions', to='industrial.company'),
        ),
        migrations.AlterField(
            model_name='companyfinancetransaction',
            name='payment_for_job',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='payment', to='industrial.job'),
        ),
        migrations.AlterField(
            model_name='companyfinancetransaction',
            name='payment_invoice',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='transaction', to='payment.paymentinvoice'),
        ),
        migrations.AlterField(
            model_name='companynotifications',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='notifications', to='industrial.company'),
        ),
        migrations.AlterField(
            model_name='companyreferralchain',
            name='affiliate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='affiliate', to='industrial.company'),
        ),
        migrations.AlterField(
            model_name='companyreferralchain',
            name='referral',
            field=models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name='referral', to='industrial.company'),
        ),
        migrations.AlterField(
            model_name='job',
            name='ind_tags',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='ind_job_tegs', to='core_base.individualtag'),
        ),
        migrations.AlterField(
            model_name='responsetojob',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='responses', to='industrial.job'),
        ),
    ]
