# Generated by Django 3.2 on 2022-11-16 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('industrial', '0018_auto_20221116_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyfinancetransaction',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='industrial.company'),
        ),
        migrations.AlterField(
            model_name='companyreferralchain',
            name='affiliate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='affiliate', to='industrial.company'),
        ),
        migrations.AlterField(
            model_name='companyreferralchain',
            name='referral',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referral', to='industrial.company'),
        ),
    ]
