# Generated by Django 3.2 on 2022-11-16 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('industrial', '0020_auto_20221116_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responsetojob',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='industrial.job'),
        ),
    ]
