# Generated by Django 3.2 on 2022-11-19 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_base', '0016_alter_individualtag_title'),
        ('industrial', '0021_alter_responsetojob_job'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='ind_tags',
        ),
        migrations.AddField(
            model_name='job',
            name='ind_tags',
            field=models.ManyToManyField(related_name='ind_job_tegs', to='core_base.IndividualTag'),
        ),
    ]
