# Generated by Django 3.2 on 2022-11-19 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core_base', '0016_alter_individualtag_title'),
        ('industrial', '0023_job_all_ind_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='all_ind_tags',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='all_ind_job_tegs', to='core_base.individualtag'),
        ),
    ]
