# Generated by Django 3.2 on 2022-11-19 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_base', '0016_alter_individualtag_title'),
        ('industrial', '0024_alter_job_all_ind_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='all_ind_tags',
        ),
        migrations.AddField(
            model_name='job',
            name='all_ind_tags',
            field=models.ManyToManyField(related_name='all_ind_job_tegs', to='core_base.IndividualTag'),
        ),
    ]
