# Generated by Django 3.2 on 2022-11-21 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core_base', '0016_alter_individualtag_title'),
        ('industrial', '0026_auto_20221121_1117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='all_ind_tags',
        ),
        migrations.AddField(
            model_name='job',
            name='all_ind_tags',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='all_ind_job_tegs', to='core_base.individualtag'),
        ),
        migrations.RemoveField(
            model_name='job',
            name='ind_tags',
        ),
        migrations.AddField(
            model_name='job',
            name='ind_tags',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ind_job_tegs', to='core_base.individualtag'),
        ),
    ]
