# Generated by Django 3.2 on 2022-11-21 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_base', '0016_alter_individualtag_title'),
        ('industrial', '0029_auto_20221121_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='all_ind_tags',
            field=models.ManyToManyField(blank=True, null=True, related_name='all_ind_job_tegs', to='core_base.IndividualTag'),
        ),
        migrations.AlterField(
            model_name='job',
            name='ind_tags',
            field=models.ManyToManyField(blank=True, null=True, related_name='ind_job_tegs', to='core_base.IndividualTag'),
        ),
        migrations.AlterField(
            model_name='job',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, related_name='job_tegs', to='core_base.Tag'),
        ),
    ]
