# Generated by Django 3.2 on 2022-11-22 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('industrial', '0032_auto_20221121_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='qualification',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
    ]
