# Generated by Django 3.2 on 2022-11-22 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('industrial', '0034_alter_job_qualification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='qualification',
            field=models.CharField(default='', max_length=64),
        ),
    ]
