# Generated by Django 3.2 on 2022-11-24 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('industrial', '0036_auto_20221122_1659'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='seo_description',
            field=models.CharField(max_length=4000, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='seo_keywords',
            field=models.CharField(max_length=4000, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='seo_title',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='expire_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='published_at',
            field=models.DateTimeField(null=True),
        ),
    ]
