# Generated by Django 3.2 on 2022-11-24 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('industrial', '0038_auto_20221124_0140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='all_ind_tags',
        ),
        migrations.RemoveField(
            model_name='job',
            name='ind_tags',
        ),
    ]
