# Generated by Django 3.2 on 2022-11-24 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('industrial', '0038_auto_20221124_0140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='seo_image',
            field=models.FileField(blank=True, null=True, upload_to='meta_images'),
        ),
    ]
