# Generated by Django 3.2 on 2022-11-24 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('industrial', '0039_alter_job_seo_image'),
        ('industrial', '0039_auto_20221124_1048'),
    ]

    operations = [
    ]
