# Generated by Django 3.2 on 2022-11-24 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_base', '0016_alter_individualtag_title'),
        ('industrial', '0040_merge_20221124_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='all_ind_tags',
            field=models.ManyToManyField(blank=True, related_name='all_ind_job_tegs', to='core_base.IndividualTag'),
        ),
        migrations.AddField(
            model_name='job',
            name='ind_tags',
            field=models.ManyToManyField(blank=True, related_name='ind_job_tegs', to='core_base.IndividualTag'),
        ),
    ]
