# Generated by Django 3.2 on 2022-11-28 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('industrial', '0041_auto_20221124_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='is_agree_with_agreement',
            field=models.BooleanField(default=False),
        ),
    ]
