# Generated by Django 3.2 on 2022-10-21 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('IND', 'Industrial'), ('APPLICANT', 'Applicant'), ('ADMIN', 'Admin')], max_length=20),
        ),
    ]
