# Generated by Django 3.2 on 2022-10-27 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_base', '0002_alter_user_user_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=100)),
                ('show_on_main_page', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Тег соискателя',
                'verbose_name_plural': 'Теги соискателя',
            },
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'Тег компании', 'verbose_name_plural': 'Теги компании'},
        ),
    ]
