# Generated by Django 3.2 on 2022-10-31 05:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('industrial', '0010_remove_applicant_category'),
        ('core_base', '0003_auto_20221027_0831'),
    ]

    operations = [
        migrations.CreateModel(
            name='EducationLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': 'Уровень образования',
                'verbose_name_plural': 'Уровень образования',
            },
        ),
        migrations.CreateModel(
            name='JobExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('position', models.CharField(max_length=150)),
                ('function', models.CharField(max_length=150)),
                ('start_data', models.DateField()),
                ('end_data', models.DateField()),
                ('applicant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exp_app', to='industrial.applicant')),
            ],
            options={
                'verbose_name': 'Место работы',
                'verbose_name_plural': 'Места работы',
            },
        ),
        migrations.CreateModel(
            name='EducationPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('faculty', models.CharField(max_length=150)),
                ('specialization', models.CharField(max_length=150)),
                ('start_data', models.DateField()),
                ('end_data', models.DateField()),
                ('applicant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='edu_app', to='industrial.applicant')),
                ('level', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='edu_app', to='core_base.educationlevel')),
            ],
            options={
                'verbose_name': 'Место учебы',
                'verbose_name_plural': 'Места учебы',
            },
        ),
    ]
