# Generated by Django 3.2 on 2022-11-01 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_base', '0005_alter_jobexperience_function'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationplace',
            name='have_education',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jobexperience',
            name='have_experience',
            field=models.BooleanField(default=False),
        ),
    ]
