# Generated by Django 3.2 on 2022-11-01 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_base', '0006_auto_20221101_0943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationplace',
            name='start_data',
            field=models.DateField(verbose_name="['%d-%m-%Y']"),
        ),
    ]
