# Generated by Django 3.2 on 2022-11-10 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_base', '0009_remove_educationplace_have_education'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndividualTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=100)),
                ('show_on_main_page', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Персональный Тег',
                'verbose_name_plural': 'Персональные Теги',
            },
        ),
    ]
