# Generated by Django 3.2 on 2022-11-11 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('industrial', '0014_auto_20221110_0854'),
        ('core_base', '0010_individualtag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='blogs', to='core_base.blogcategory'),
        ),
        migrations.AlterField(
            model_name='educationplace',
            name='applicant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='edu_app', to='industrial.applicant'),
        ),
    ]
