# Generated by Django 3.2 on 2022-11-11 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('industrial', '0015_auto_20221111_1447'),
        ('core_base', '0011_auto_20221111_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationplace',
            name='applicant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='edu_app', to='industrial.applicant'),
        ),
    ]
