# Generated by Django 3.2 on 2022-11-19 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_base', '0012_alter_educationplace_applicant'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='individualtag',
            options={'verbose_name': 'Персональный тег', 'verbose_name_plural': 'Персональные теги'},
        ),
        migrations.AlterField(
            model_name='individualtag',
            name='title',
            field=models.CharField(max_length=30),
        ),
    ]
