# Generated by Django 3.2 on 2022-11-19 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_base', '0013_auto_20221119_0850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individualtag',
            name='show_on_main_page',
            field=models.BooleanField(default=True),
        ),
    ]
