# Generated by Django 3.2 on 2022-11-19 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_base', '0014_alter_individualtag_show_on_main_page'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='individualtag',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='individualtag',
            name='updated_at',
        ),
    ]
