# Generated by Django 3.2 on 2022-11-19 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_base', '0015_auto_20221119_0853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individualtag',
            name='title',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
