# Generated by Django 3.2 on 2022-10-20 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('url', models.CharField(max_length=150)),
                ('icon_code', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Social links',
                'verbose_name_plural': 'Social links',
            },
        ),
        migrations.CreateModel(
            name='TemplateParts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('title', models.CharField(max_length=150)),
                ('content', models.TextField(max_length=50000)),
            ],
            options={
                'verbose_name': 'Часты шаблона',
                'verbose_name_plural': 'Часты шаблона',
            },
        ),
    ]
