# Generated by Django 3.2 on 2022-11-11 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bulletin_board', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='templateparts',
            options={'verbose_name': 'Части шаблонов', 'verbose_name_plural': 'Часть шаблона'},
        ),
    ]
