# Generated by Django 3.2 on 2022-11-11 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bulletin_board', '0002_alter_templateparts_options'),
        ('bulletin_board', '0002_indexfile'),
    ]

    operations = [
    ]
