# Generated by Django 3.2 on 2022-11-18 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletin_board', '0004_seometa'),
    ]

    operations = [
        migrations.AddField(
            model_name='seometa',
            name='image',
            field=models.FileField(null=True, upload_to='meta_images'),
        ),
    ]
