# Generated by Django 3.2 on 2022-10-20 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('industrial', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('waiting', 'Ожидается'), ('succeed', 'Успешно'), ('canceled', 'Отменен')], max_length=20)),
                ('amount', models.FloatField()),
                ('comment', models.CharField(max_length=500)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_invoices', to='industrial.company')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TinkoffCardPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('terminal_key', models.CharField(max_length=20)),
                ('status', models.CharField(blank=True, max_length=20, null=True)),
                ('tinkoff_payment_id', models.CharField(blank=True, max_length=20, null=True)),
                ('tinkoff_payment_url', models.CharField(blank=True, max_length=150, null=True)),
                ('order_id', models.CharField(max_length=40)),
                ('amount', models.FloatField()),
                ('description', models.CharField(max_length=250)),
                ('payment_invoice', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='tinkoff_card_payment', to='payment.paymentinvoice')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
